
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "babbd1c68adc50c0e2199676c7ae741194c520da",
 "version": "3.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
