name: CLI tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libsndfile
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1
      - name: Install pyannote.audio
        run: |
          pip install -e .[dev,testing,cli]
      - name: Test with pytest
        run: |
          pytest tests/test_cli.py
