params:
  clustering:
    method: centroid
    min_cluster_size: 12
    threshold: 0.7045654963945799
  segmentation:
    min_duration_off: 0.0
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: speaker-embedding.onnx
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: segmentation.onnx
    segmentation_batch_size: 32
version: 3.1.0
