
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4b0fd5302d8fa3ba249b42d3ab7b4cb51ee61ba2",
 "version": "5.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
